from typing import Optional, Protocol


class VCSClient(Protocol):
    def fetch_pr_diff(self, pr_id: str) -> dict: ...

    def fetch_pr_metadata(self, pr_id: str) -> tuple[str, str]: ...

    def fetch_pr_activities(self, pr_id: str, limit: int = 1000) -> list[dict]: ...

    def post_comment(
        self, pr_id: str, text: str, anchor: Optional[dict] = None
    ) -> dict: ...

    def update_comment(
        self, pr_id: str, comment_id: str, text: str, version: Optional[int] = None
    ) -> dict: ...

    def delete_comment(self, pr_id: str, comment_id: str, version: int) -> None: ...

    def get_vcs_config(self) -> dict: ...
